USE my_db;
-- BEST PRACTICE TO USE SELECT QUERY TO KNOW ON WHICH DATA WE ARE GOING TO FIRE QUERY THEN USE THE DELETE COMMAND -- 

DELETE FROM users
 WHERE id = 1;
SELECT * FROM users;

DELETE FROM users
WHERE salary IS NULL;

SELECT * FROM users;